TARGET = intraFontTest
OBJS = fonttest.o 

INCDIR = ../../include
CFLAGS = -O2 -G0 -Wall -Wextra -g -D_PSP -DPSP

BUILD_PRX = 1
PSP_FW_VERSION = 500

LIBDIR = ../../lib
LDFLAGS = 
LIBS = -lintrafont -lpspgum -lpspgu -lpng -lz -lm

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = intraFont-G Test

BUILD_PRX = 1
PSP_FW_VERSION = 500

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak

